version: '2.1'

services:
    sabarish:
        container_name: sabarish
        privileged: true
        cap_add:
             - NET_ADMIN
             - SYS_ADMIN
        build: .
        hostname: labs1
        ports:
            - "22:22"
            - "51820:51820"

    db:
        platform: linux/x86_64
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        
        
